app.control.webphone=new Class({Implements:[Options,Events],options:{request:{url:"index.php",data:{option:"com_appbuilder",controller:"appserver"},method:"get",concurrent:10,timeout:15E3,timeoutUpdate:5E3},fullscreen:!1,background:!0,statusbar:!0,storage:!1,files:!1,update:!1,updateSingle:!1,browserHistory:!1,splash:!1,style:"auto",homeButton:!1,horizontal:!1,fixed:!1},initialize:function(a){appbuilder.app.debug("phone","init");this.setOptions(a);this.temporaryStorage=appbuilder.app.Storage;this.temporaryStorage.phone=
this;this.options.storage&&appbuilder.app.LocalStorage&&(this.storage=appbuilder.app.LocalStorage,this.storage.phone=this);this.history=new appbuilder.app.History(this);this.loader=new appbuilder.app.Loader(this);this.navigator=new appbuilder.app.Navigator(this);appbuilder.app.Analytics.attach(this);appbuilder.app.current||(appbuilder.app.current=this)},toElement:function(){if(!this.element){this.element=appbuilder.app.makeElement("phone");appbuilder.app.isPhoneGap&&this.element.addClass("phonegap");
Browser.Platform.ios&&this.element.addClass("ios");(Browser.Platform.ipodIos7||Browser.Platform.iphoneIos7||Browser.Platform.iPadIos7)&&this.element.addClass("ios7");Browser.Platform.android&&this.element.addClass("android-os");Browser.Platform.blackberry&&(this.element.addClass("blackberry-os"),Browser.Platform.playBook?this.element.addClass("blackberry-os-playbook"):Browser.Platform.smartphone?this.element.addClass("blackberry-os-smartphone"):Browser.Platform.BB10&&this.element.addClass("blackberry-os-bb10"),
7.2>Browser.version&&(this.options.fixed=!0));this.options.fixed&&(this.element.addClass("fixed"),appbuilder.app.startHeightTracker());if(this.options.fullscreen){this.element.addClass("fullscreen ios");if(appbuilder.app.isMobile&&!this.options.fixed){if(!appbuilder.app.isPhoneGap&&!window.navigator.standalone&&(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i))){var a=function(){Browser.Platform.ipodIos7||Browser.Platform.iphoneIos7?(this.element.addClass("fullscreen ios"),
window.innerHeight>window.innerWidth?(this.element.setStyle("height",window.getSize().y),this.element.removeClass("auto-height")):(this.element.removeProperty("height"),this.element.addClass("auto-height"))):this.element.setStyle("height",window.getSize().y)}.bind(this);this.addEvent("resize",a);a()}a=function(){!Browser.Platform.ipodIos7&&(!Browser.Platform.iphoneIos7&&window.innerHeight<window.innerWidth)&&window.scrollTo(0,1)};a.delay(100);this.element.addEvent("touchstart",a);this.element.addEvent("touchmove",
function(a){!Browser.Platform.ipodIos7&&(!Browser.Platform.iphoneIos7&&window.innerHeight<window.innerWidth)&&a.preventDefault()})}window.addEvent("resize",function(a){this.fireEvent("resize",[a])}.bind(this))}else"half"==this.options.background?this.element.addClass("background half"):!0!==this.options.background&&"full"!=this.options.background||this.element.addClass("background full");this.setStyle(this.options.style,!0);this.setHorizontal(this.options.horizontal,!0);this.setRealSize(this.options.realSize,
!0);a=appbuilder.app.makeElement("phone-inner").inject(this.element);this.status=appbuilder.app.makeElement("status-bar",{html:(new Date).format("%H:%M")}).inject(a);(function(){this.status.set("html",(new Date).format("%H:%M"))}).periodical(6E4,this);this.options.statusbar&&this.element.addClass("status");document.id(this.loader).inject(a);document.id(this.navigator).inject(a);this.options.homeButton&&appbuilder.app.makeElement("home-button",{"data-linktype":"app","data-href":1,"data-no-glow":"no-glow"}).inject(this.element);
this.history.checkHistory()||void 0==this.options.app||this.navigator.linktypes.app.apply(this.navigator,[this.options.app,!0,this.options.screen?function(){this.navigator.linktypes.screen.apply(this.navigator,[this.options.screen,!1])}.bind(this):null])}return this.element},setStyle:function(a,b){appbuilder.app.debug("phone","style",a);var c="iphone iphone5 ipad android androidsm blackberry blackberry10 playbook nexus7 auto".split(" ");-1!=c.indexOf(a)&&(this.options.style=a,"auto"==a&&(a=Browser.Platform.android?
4>Browser.version?"androidsm":"android":Browser.Platform.blackberry?Browser.Platform.playBook||Browser.Platform.BB10||10<=Browser.version?"blackberry10":"blackberry":"iphone"),this.element&&(c.each(function(a){this.element.removeClass(a)},this),this.element.addClass(a),"nexus7"==a?this.element.addClass("android"):"playbook"==a&&this.element.addClass("blackberry10"),this.options.background&&("half"===this.options.background&&this.element.addClass("half"),this.element.addClass("background")),!b&&this.fireEvent("resize")))},
setHorizontal:function(a,b){this.options.horizontal=a;this.element&&(a?this.element.addClass("horizontal"):this.element.removeClass("horizontal"),!b&&this.fireEvent("resize"))},setRealSize:function(a,b){this.options.realSize=a;this.element&&(a?this.element.addClass("realsize"):this.element.removeClass("realsize"),!b&&this.fireEvent("resize"))},updateApp:function(a,b,c){this.options.update&&this.storage&&appbuilder.app.online()?(appbuilder.app.debug("phone","update","starting"),this.loader.showLoading(),
this.temporaryStorage.clear(),this.getLastUpdate(a,function(c){var e=function(c){c?(appbuilder.app.debug("phone","update","updating"),Object.each(c,function(b,c){"time"==c?this.setLastUpdate(a,b):Object.each(b,function(a,b){this.loaded(a)},this)},this),this.storage.flush(),this.loader.hideLoading(),b(!0)):(appbuilder.app.debug("phone","update","nothing"),this.loader.hideLoading(),b(!1))}.bind(this),f=function(a){appbuilder.app.debug("phone","update","error",a);this.loader.hideLoading();b(!1)}.bind(this);
this.loader.request("update",a,c,e,f,null,this.options.request.timeoutUpdate)}.bind(this))):(appbuilder.app.debug("phone","update","disabled"),b(!1))},getLastUpdate:function(a,b){this.storage?this.storage.fetch("update",a,function(c){c?b(c.update):(this.storage.store("update",a,{update:this.options.published}),b(this.options.published))}.bind(this)):b(this.options.published)},setLastUpdate:function(a,b){this.storage&&this.storage.store("update",a,{update:b})},getUniqueId:function(){if(this.uniqueId)return this.uniqueId;
if(appbuilder.app.isPhoneGap)return device.uuid;if(this.storage&&(this.uniqueId=this.storage.fetch("device","unique")))return this.uniqueId;var a=new Date;this.uniqueId=(a++).toString(36)+(new Date).getMilliseconds().toString(36);this.storage&&this.storage.store("device","unique",this.uniqueId);return this.uniqueId},fetch:function(a,b,c,d,e,f){c=this.loadingcb(c);var g=this.temporaryStorage.fetch(a,b);if(g)c(g);else{if(this.storage&&(g=this.storage.fetch(a,b))){this.updateSingle(a,b,g,c,d);return}this.options.files&&
!e?appbuilder.app.FileLoader.fetch(a,b,function(e){e?this.updateSingle(a,b,e,c,d):appbuilder.app.online()?this.loader.fetch(a,b,c,null,d):c(!1)}.bind(this),d,this):e&&appbuilder.app.online()?this.fetchLive(f?"direct":"remote",e,function(d,e){e&&e[a]?c(e[a][b]):c(!1)}.bind(this)):appbuilder.app.online()?this.loader.fetch(a,b,c,null,d):c(!1)}},fetchLive:function(a,b,c,d,e){if(!e){var f=this.temporaryStorage.fetch("direct"==a?"remote":a,b);if(f){c(f);return}if(this.storage&&(f=this.storage.fetch("direct"==
a?"remote":a,b))){c(f);return}}appbuilder.app.online()?this.loader.fetch(a,b,function(d,f){d?c(d,f):!e&&this.options.files?appbuilder.app.FileLoader.fetch("direct"==a?"remote":a,b,c,null,this):c(!1)}.bind(this),!1,!1,d):!e&&this.options.files?appbuilder.app.FileLoader.fetch("direct"==a?"remote":a,b,c,null,this):c(!1)},loadingcb:function(a){this.loader.showLoading();return function(){this.loader.hideLoading();a.apply(this,arguments)}.bind(this)},updateSingle:function(a,b,c,d,e){appbuilder.app.online()&&
c.updated&&this.options.updateSingle?(appbuilder.app.debug("phone","updateSingle","starting"),this.loader.fetch(a,b,function(e){e?(appbuilder.app.debug("phone","updateSingle","updated"),d(e)):(appbuilder.app.debug("phone","updateSingle","nothing"),this.temporaryStorage.store(a,b,c),d(c))}.bind(this),c.updated,e)):(appbuilder.app.debug("phone","updateSingle","disabled"),this.temporaryStorage.store(a,b,c),d(c))},loaded:function(a,b,c){this.temporaryStorage.storeObj(a);this.storage&&!c&&this.storage.storeObj(a);
b&&(this.flushStorage(),a.app&&a.app[this.history.currentApp]?this.history.refresh():a.screen&&a.screen[this.history.currentScreen()]&&this.history.refreshScreen())},flushStorage:function(){appbuilder.app.debug("phone","flush");this.temporaryStorage.flush();this.storage&&this.storage.flush()},clearStorage:function(){appbuilder.app.debug("phone","clear");this.temporaryStorage.clear();this.storage&&this.storage.clear()}},"Phone");appbuilder=window.appbuilder||{};appbuilder.app=appbuilder.app||{};
